export const mockData = {
  skills: [
    {
      uniqueId: 1,
      skill: "C",
      id: "skill-1",
      proficient: true,
      fieldType: "Languages",
      image: { url: "SiC" },
      url: "https://en.wikipedia.org/wiki/C_(programming_language)",
    },
    {
      uniqueId: 2,
      skill: "C++",
      id: "skill-2",
      proficient: true,
      fieldType: "Languages",
      image: { url: "SiCplusplus" },
      url: "https://isocpp.org/",
    },
    {
      uniqueId: 3,
      skill: "Python",
      id: "skill-3",
      proficient: true,
      fieldType: "Languages",
      image: { url: "SiPython" },
      url: "https://www.python.org/",
    },
    {
      uniqueId: 4,
      skill: "SQL",
      id: "skill-4",
      proficient: true,
      fieldType: "Languages",
      image: { url: "SiPostgresql" },
      url: "https://en.wikipedia.org/wiki/SQL",
    },
    {
      uniqueId: 5,
      skill: "Scala",
      id: "skill-5",
      proficient: true,
      fieldType: "Languages",
      image: { url: "SiScala" },
      url: "https://www.scala-lang.org/",
    },
    {
      uniqueId: 6,
      skill: "Java",
      id: "skill-6",
      proficient: true,
      fieldType: "Languages",
      image: { url: "SiOpenjdk" },
      url: "https://www.java.com/",
    },
    {
      uniqueId: 7,
      skill: "R",
      id: "skill-7",
      proficient: true,
      fieldType: "Languages",
      image: { url: "SiR" },
      url: "https://www.r-project.org/",
    },
    {
      uniqueId: 8,
      skill: "HTML",
      id: "skill-8",
      proficient: true,
      fieldType: "Frontend",
      image: { url: "SiHtml5" },
      url: "https://developer.mozilla.org/en-US/docs/Web/HTML",
    },
    {
      uniqueId: 9,
      skill: "CSS",
      id: "skill-9",
      proficient: true,
      fieldType: "Frontend",
      image: { url: "SiCss3" },
      url: "https://developer.mozilla.org/en-US/docs/Web/CSS",
    },
    {
      uniqueId: 10,
      skill: "JavaScript",
      id: "skill-10",
      proficient: true,
      fieldType: "Frontend",
      image: { url: "SiJavascript" },
      url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
    },
    {
      uniqueId: 21,
      skill: "React",
      id: "skill-21",
      proficient: true,
      fieldType: "Frontend",
      image: { url: "SiReact" },
      url: "https://react.dev/",
    },
    {
      uniqueId: 22,
      skill: "TypeScript",
      id: "skill-22",
      proficient: true,
      fieldType: "Frontend",
      image: { url: "SiTypescript" },
      url: "https://www.typescriptlang.org/",
    },
    {
      uniqueId: 23,
      skill: "React Router",
      id: "skill-23",
      proficient: true,
      fieldType: "Frontend",
      image: { url: "SiReactrouter" },
      url: "https://reactrouter.com/",
    },
    {
      uniqueId: 24,
      skill: "Chakra UI",
      id: "skill-24",
      proficient: true,
      fieldType: "Frontend",
      image: { url: "SiChakraui" },
      url: "https://chakra-ui.com/",
    },
    {
      uniqueId: 11,
      skill: "Firebase",
      id: "skill-11",
      proficient: true,
      fieldType: "Backend",
      image: { url: "SiFirebase" },
      url: "https://firebase.google.com/",
    },
    {
      uniqueId: 12,
      skill: "Supabase",
      id: "skill-12",
      proficient: true,
      fieldType: "Backend",
      image: { url: "SiSupabase" },
      url: "https://supabase.com/",
    },
    {
      uniqueId: 25,
      skill: "Django",
      id: "skill-25",
      proficient: true,
      fieldType: "Backend",
      image: { url: "SiDjango" },
      url: "https://www.djangoproject.com/",
    },
    {
      uniqueId: 26,
      skill: "Django REST",
      id: "skill-26",
      proficient: true,
      fieldType: "Backend",
      image: { url: "SiDjango" },
      url: "https://www.django-rest-framework.org/",
    },
    {
      uniqueId: 27,
      skill: "JWT",
      id: "skill-27",
      proficient: true,
      fieldType: "Backend",
      image: { url: "SiJsonwebtokens" },
      url: "https://jwt.io/",
    },
    {
      uniqueId: 13,
      skill: "Swift",
      id: "skill-13",
      proficient: true,
      fieldType: "Mobile",
      image: { url: "SiSwift" },
      url: "https://swift.org/",
    },
    {
      uniqueId: 14,
      skill: "Kotlin",
      id: "skill-14",
      proficient: true,
      fieldType: "Mobile",
      image: { url: "SiKotlin" },
      url: "https://kotlinlang.org/",
    },
    {
      uniqueId: 15,
      skill: "SwiftUI",
      id: "skill-15",
      proficient: true,
      fieldType: "Mobile",
      image: { url: "SiSwift" },
      url: "https://developer.apple.com/swiftui/",
    },
    {
      uniqueId: 16,
      skill: "Jetpack Compose",
      id: "skill-16",
      proficient: true,
      fieldType: "Mobile",
      image: { url: "SiKotlin" },
      url: "https://developer.android.com/jetpack/compose",
    },
    {
      uniqueId: 17,
      skill: "Pandas",
      id: "skill-17",
      proficient: true,
      fieldType: "Machine Learning",
      image: { url: "SiPython" },
      url: "https://pandas.pydata.org/",
    },
    {
      uniqueId: 18,
      skill: "NumPy",
      id: "skill-18",
      proficient: true,
      fieldType: "Machine Learning",
      image: { url: "SiPython" },
      url: "https://numpy.org/",
    },
    {
      uniqueId: 19,
      skill: "Git",
      id: "skill-19",
      proficient: true,
      fieldType: "Others",
      image: { url: "SiGit" },
      url: "https://git-scm.com/",
    },
    {
      uniqueId: 20,
      skill: "Docker",
      id: "skill-20",
      proficient: true,
      fieldType: "Others",
      image: { url: "SiDocker" },
      url: "https://www.docker.com/",
    },
  ],
  jobs: [
    {
      id: "job-1",
      company: "Syntax Institut",
      designation: "Mobile Engineer Instructor",
      companyLinkedin: "",
      companyUrl: "",
      from: "2022-12-01",
      to: "",
      logo: { url: "/assets/syntax.webp" },
    },
    {
      id: "job-2",
      company: "Vrije University Amsterdam",
      designation: "Teaching Assistant",
      companyLinkedin: "",
      companyUrl: "",
      from: "2021-11-01",
      to: "2021-12-01",
      logo: { url: "/assets/vu.webp" },
    },
    {
      id: "job-3",
      company: "DKV Mobility",
      designation: "Database Engineer",
      companyLinkedin: "",
      companyUrl: "",
      from: "2019-07-01",
      to: "2019-08-01",
      logo: { url: "/assets/dkv.webp" },
    },
  ],
  projects: [
    {
      id: "proj-5",
      title: "Vector Image Editor (ongoing)",
      uniqueId: 5,
      description:
        "Building a full-stack vector image editor using React and Python. Provides a chat interface for interacting and editing vector images.",
      demoLink: "",
      videoUrl: "",
      githubLink: "",
      techStack: [
        { text: "All" },
        { text: "Full-Stack" },
        { text: "React" },
        { text: "TypeScript" },
        { text: "Django" },
        { text: "Django REST" },
        { text: "React Router" },
        { text: "Chakra UI" },
        { text: "PostgreSQL" },
        { text: "JWT" },
      ],
      image: { url: "/assets/nextUp-mockup.png" },
    },
    {
      id: "proj-1",
      title: "Tetris",
      uniqueId: 1,
      description: "A Tetris game implemented in Scala with: instant drop and line clearing.",
      demoLink: "",
      videoUrl: "/videos/tetris-demo.mp4",
      githubLink: "https://github.com/notJustus/OOFP_tetris",
      techStack: [
        { text: "All" },
        { text: "Scala" },
        { text: "OOP" },
        { text: "Functional Programming" },
        { text: "Immutable Design" },
        { text: "Games" },
      ],
      image: { url: "/assets/tetris-preview.webp" },
    },
    {
      id: "proj-2",
      title: "Snake",
      uniqueId: 2,
      description: "Reimplementation of famous Snake game.",
      demoLink: "",
      videoUrl: "/videos/snake-demo.mp4",
      githubLink: "https://github.com/notJustus/OOFP_snake",
      techStack: [
        { text: "All" },
        { text: "Scala" },
        { text: "OOP" },
        { text: "Functional Programming" },
        { text: "Immutable Design" },
        { text: "Games" },
      ],
      image: { url: "/assets/snake-preview.webp" },
    },
    {
      id: "proj-3",
      title: "Malloc",
      uniqueId: 3,
      description:
        "Custom heap allocator that manages: requesting and freeing memory using system calls.",
      demoLink: "",
      videoUrl: "",
      githubLink: "",
      techStack: [
        { text: "All" },
        { text: "C" },
        { text: "Operating System" },
        { text: "Memory Allocation" },
        { text: "System Level" },
      ],
      image: { url: "/assets/profilePic.webp" },
    },
    {
      id: "proj-4",
      title: "Filesystem",
      uniqueId: 4,
      description:
        "Custom file system based on FAT with (sub)directories and files of arbitrary size. Supports file operations, directory traversal, and persistent storage.",
      demoLink: "",
      videoUrl: "",
      githubLink: "",
      techStack: [
        { text: "All" },
        { text: "C" },
        { text: "Operating System" },
        { text: "File System" },
        { text: "System Level" },
      ],
      image: { url: "/assets/profilePic.webp" },
    },
  ],
};
