export const mockData = {
  jobs: [
    {
      id: "job-1",
      company: "Philips",
      designation: "AI Engineer Intern",
      companyLinkedin: "",
      companyUrl: "",
      from: "2026-03-01",
      to: "2026-08-01",
      logo: { url: "/assets/phillips-logo.webp" },
    },
    {
      id: "job-2",
      company: "Syntax Institut",
      designation: "Mobile Engineering Instructor",
      companyLinkedin: "",
      companyUrl: "",
      from: "2022-12-01",
      to: "2026-02-01",
      logo: { url: "/assets/syntax.webp" },
    },
    {
      id: "job-3",
      company: "Vrije University Amsterdam",
      designation: "Teaching Assistant",
      companyLinkedin: "",
      companyUrl: "",
      from: "2021-11-01",
      to: "2021-12-01",
      logo: { url: "/assets/vu.webp" },
    },
    {
      id: "job-4",
      company: "DKV Mobility",
      designation: "Database Engineer Intern",
      companyLinkedin: "",
      companyUrl: "",
      from: "2019-07-01",
      to: "2019-08-01",
      logo: { url: "/assets/dkv.webp" },
    },
  ],
  projects: [
    {
      id: "proj-1",
      title: "PintKing",
      uniqueId: 1,
      description:
        "Social iOS app where every drink is logged with a photo, scored on a group leaderboard, and pinned to a map of past nights out.",
      demoLink: "",
      videoUrl: "",
      githubLink: "https://github.com/notJustus/pint-king",
      techStack: [
        { text: "All" },
        { text: "Full-Stack" },
        { text: "Swift" },
        { text: "SwiftUI" },
        { text: "Kotlin" },
        { text: "Spring Boot" },
        { text: "REST" },
        { text: "PostgreSQL" },
        { text: "JWT" },
        { text: "S3" },
      ],
      image: { url: "" },
    },
    {
      id: "proj-2",
      title: "AgentLink",
      uniqueId: 2,
      description:
        "Master's thesis internship at Philips: a ReAct agent in LangGraph that recovers traceability links between requirements and source code, a process previously maintained by hand.",
      demoLink: "",
      videoUrl: "",
      githubLink: "",
      techStack: [
        { text: "All" },
        { text: "AI" },
        { text: "Python" },
        { text: "LangGraph" },
        { text: "ReAct Agents" },
        { text: "LangSmith" },
        { text: "AWS Bedrock AgentCore" },
      ],
      image: { url: "" },
    },
  ],
};
